# Generated by Django 4.0 on 2023-11-14 01:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='aluno', max_length=30)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=500)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estrutura', models.JSONField()),
                ('etapas', models.JSONField()),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_criacao', models.DateField(auto_now_add=True)),
                ('caminho', models.CharField(blank=True, max_length=100, null=True)),
                ('num_etapas', models.IntegerField(default=1)),
                ('num_pergs', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Diagrama',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('codigo', models.CharField(default='3wa', max_length=300)),
                ('responsavel', models.ForeignKey(db_column='fk_usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='app.user')),
            ],
            options={
                'db_table': 'Turma',
                'order_with_respect_to': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descendente', models.ForeignKey(blank=True, db_column='fk_pasta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pasta')),
                ('dono', models.ForeignKey(db_column='fk_usuario_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Pasta',
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.ForeignKey(blank=True, db_column='fk_aluno_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('turma', models.ForeignKey(blank=True, db_column='fk_turma_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'verbose_name_plural': 'participantes',
                'db_table': 'Participa',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_alteracao', models.DateField(auto_now_add=True)),
                ('criador', models.ForeignKey(db_column='fk_usuario_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('diagrama', models.ForeignKey(db_column='fk_diagrama_id', on_delete=django.db.models.deletion.CASCADE, to='app.diagrama')),
            ],
            options={
                'db_table': 'Gerencia',
                'ordering': ['-dt_alteracao'],
            },
        ),
        migrations.AddField(
            model_name='diagrama',
            name='pasta',
            field=models.ForeignKey(blank=True, db_column='fk_pasta_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pasta'),
        ),
        migrations.CreateModel(
            name='AcessoPasta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_atribuicao', models.DateField(auto_now_add=True)),
                ('pasta', models.ForeignKey(db_column='fk_pasta_id', on_delete=django.db.models.deletion.CASCADE, to='app.pasta')),
                ('turma', models.ForeignKey(db_column='fk_turma_id', on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'db_table': 'Acessa',
                'order_with_respect_to': 'dt_atribuicao',
            },
        ),
        migrations.CreateModel(
            name='AcessoDiagrama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_exibicao', models.DateField()),
                ('diagrama', models.ForeignKey(blank=True, db_column='fk_diagrama_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.diagrama')),
                ('turma', models.ForeignKey(blank=True, db_column='fk_turma_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'db_table': 'Visualiza',
                'order_with_respect_to': 'diagrama',
            },
        ),
    ]
