# Generated by Django 4.0 on 2023-11-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='depto',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(db_column='fk_turma_id', on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
