# Generated by Django 4.0 on 2023-11-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_matricula_disciplina_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
