# Generated by Django 4.0 on 2023-11-27 12:22

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_disciplina_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerencia',
            options={},
        ),
        migrations.RemoveField(
            model_name='diagrama',
            name='caminho',
        ),
        migrations.RemoveField(
            model_name='gerencia',
            name='dt_alteracao',
        ),
        migrations.AddField(
            model_name='acessodiagrama',
            name='dt_fim_vis',
            field=models.DateTimeField(default=app.models.AcessoDiagrama.default_dt_fim_vis),
        ),
        migrations.AddField(
            model_name='acessodiagrama',
            name='dt_ini_vis',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='acessodiagrama',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='acessopasta',
            order_with_respect_to=None,
        ),
        migrations.AlterModelTable(
            name='disciplina',
            table='Disciplina',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Usuario',
        ),
        migrations.RemoveField(
            model_name='acessodiagrama',
            name='dt_exibicao',
        ),
        migrations.RemoveField(
            model_name='acessopasta',
            name='dt_atribuicao',
        ),
    ]
