# Generated by Django 4.0 on 2023-11-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_acessodiagrama_dt_ini_vis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='aluno',
            field=models.ForeignKey(db_column='fk_aluno_id', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='turma',
            field=models.ForeignKey(db_column='fk_turma_id', on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
