# Generated by Django 4.0 on 2023-11-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='turma',
            order_with_respect_to=None,
        ),
    ]
