# Generated by Django 4.0 on 2023-12-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_turma_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(db_column='fk_disciplina_id', on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
