# Generated by Django 4.0 on 2023-12-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_turma_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipo',
        ),
    ]
